# Generated by Django 3.1.6 on 2021-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210214_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(auto_created=True, blank=True, max_length=255),
        ),
    ]
